from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://akaun.com/")
    page.goto("https://akaun.com/#/auth/login")
    page.get_by_label("Email or Mobile Number").click()
    page.get_by_label("Email or Mobile Number").fill("norizzaty+playwright@wavelet.net")
    page.get_by_label("Password").click()
    page.get_by_label("Password").fill("Playwright+ERP_2023")
    page.locator("form").get_by_role("button", name="Sign In").click()
    page.locator("app-icon").filter(has_text="testingInternal Sales Invoice").get_by_role("img").click()
    page.get_by_role("button", name="add").click()
    page.get_by_text("B Company (Branch 1) | B Company Sdn BhdBranch").click()
    page.get_by_text("B COMPANY (WAREHOUSE 1) | B COMPANY (WAREHOUSE 1)").click()
    page.get_by_text("L-B COMPANY (WAREHOUSE 1) | L-B COMPANY (WAREHOUSE 1)").click()
    page.get_by_role("option", name="L-B COMPANY (WAREHOUSE 1) | L-B COMPANY (WAREHOUSE 1)").get_by_text("L-B COMPANY (WAREHOUSE 1) | L-B COMPANY (WAREHOUSE 1)").click()
    page.locator("app-sales-man div").filter(has_text="Sales Agent*").nth(2).click()
    page.get_by_text("Rose").click()
    page.get_by_role("tab", name="Account").click()
    page.get_by_label("Entity Id*").click()
    page.get_by_text("1000218").click()
    page.get_by_role("cell", name="add Select Customer Select Mode ' Search... Rows 10 page 1 of 2 view Code Type Name Contact Number Code Filter Input Type Filter Input Name Filter Input Contact Number Filter Input Press SPACE to deselect this row. Press SPACE to select this row. Press SPACE to select this row. Press SPACE to select this row. Press SPACE to select this row. Press SPACE to select this row. Press SPACE to select this row. Press SPACE to select this row. Press SPACE to select this row. Press SPACE to select this row. Columns Filters").get_by_role("button", name="add").click()
    page.get_by_text("Lines").click()
    page.get_by_role("tabpanel", name="Lines").get_by_role("button", name="add").click()
    page.get_by_label("Search Serial Number").click()
    page.get_by_placeholder("Search Serial Number").fill("playwright")
    page.get_by_placeholder("Search Serial Number").press("Enter")
    page.get_by_role("cell", name="add Create Sales Invoice RESET CREATE Main Details Account Lines Settlement KO For Department Hdr Posting add Rows 10 page 1 of 1 view Total: 0.00 MYR Tax: 0.00 MYR Item Code Item Name UOM Qty Columns Filters").click()
    page.get_by_placeholder("Search Serial Number").click()
    page.get_by_placeholder("Search Serial Number").fill("")
    page.get_by_label("Search...").click()
    page.get_by_label("Search...").fill("playwright")
    page.get_by_label("Search...").press("Enter")
    page.get_by_role("gridcell", name="Testing Playwright").first.click()
    page.get_by_role("combobox", name="Pricing Scheme").locator("span").click()
    page.get_by_text("10.00 (EMP_LIST_PRICE)").click()
    page.get_by_label("Unit Price Net (Exclusive of tax)").click()
    page.get_by_label("Unit Price Net (Exclusive of tax)").fill("99")
    page.get_by_role("button", name="ADD").filter(has_text="ADD").click()
    page.get_by_role("button", name="CREATE").click()
    page.get_by_role("gridcell", name="Press Space to toggle row selection (unchecked)  1000285").get_by_role("checkbox", name="Press Space to toggle row selection (unchecked)").check()
    page.get_by_role("button", name="FINAL").click()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
